services:
  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"

  nginx-waf:
    image: owasp/modsecurity:nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./modsecurity.conf:/etc/modsecurity/modsecurity.conf:ro
      - ./crs-setup.conf:/etc/modsecurity/crs-setup.conf:ro
    depends_on:
      - juice-shop
